### PR TITLE
consider script_args config var for script exec

### LINKED ISSUE #128: [Feature request] Allow passing parameters to --script
gandi vm create allows to pass a script with --script.

Being also able to also pass parameters to that script would be very handy for automatic provisioning with pre-existing bootstrap scripts requiring parameters (amongst other use cases).

My use case: https://github.com/saltstack/salt-bootstrap

### PR DESCRIPTION
**Pull request by kalou**
must be a list of strings, that will build script argv[1:]

might help resolve https://github.com/Gandi/gandi.cli/issues/128

### CODE REVIEW

**Comment by kalou** [comment]
API's ready. Maybe time to review this - ?

**Comment by wdauchy** [comment]
I would rather rebase in one commit and explain the reason in the commit message.

**Comment by kalou** [comment]
I wish there were a button for that. Comments related to the content itself ?

**Comment by wdauchy** [comment]
sometimes you need to squash some commits and keep some others distinct.
no better ideas for args handling as well for now;

**Pull request merged**
